env = 'TestNet'
algod_url = "https://testnet-algorand.api.purestake.io/ps2"
algod_token = "4DDWlske7J1zToVwoFxb2NeDkBiYok82FnsO4mLj"
algod_port = 443
indexer_url = "https://testnet-algorand.api.purestake.io/idx2"
indexer_token = "4DDWlske7J1zToVwoFxb2NeDkBiYok82FnsO4mLj"
indexer_port = 443
app_id = 149704686
wallet_id = ""  # invalid
account_a_address = "PQTU6KMR5TMGZAT3HA5UIUVLYK5HCO5DDL5J6GAWII4YRPUBUOBBCB6GGI"
account_a_mnemonic = "truly theme chicken close phone peasant foster filter perfect expire favorite motion beach indicate enough portion absurd advice capital crash unit weekend buddy able clog"
account_b_address = ""
account_b_mnemonic = ""
account_c_address = "KEFYFQDQ6EQCUJTHJWW6C2V7OXNCR4RI2ZDOHXHZ4K2E3SNR7ZFIGEMUB4"
account_c_mnemonic = "sustain blossom neutral pave clown slide price rail fever side brain jar post table meadow diamond connect ignore zone member fish school virtual ability you"
ASA_1 = 95939489  # MIALGO ASA asset-id
ASA_2 = 106109680  # ALB ASA asset-id
pool_1 = "YJ6LDUQDRTC6TNGV7TQVOBGKM7HAQ2UR6M54CMF47TU4GBFZZXYZD5TG34"
pool_2 = "LH6JRFJ2EN4NSTBVDB5WPJMDIXUC76UEDWU2Q74MQKBL7PAVPLQQCDPO2I"
