algod_url = "https://testnet-algorand.api.purestake.io/ps2"
algod_token = "4DDWlske7J1zToVwoFxb2NeDkBiYok82FnsO4mLj"
algod_port = 443
indexer_url = "https://testnet-algorand.api.purestake.io/idx2"
indexer_token = "4DDWlske7J1zToVwoFxb2NeDkBiYok82FnsO4mLj"
indexer_port = 443
app_id = 146
wallet_id = "wallet_QWEASD"
account_a_address = "I6GQAHTW7YHHHX6G5J6VJH7TA3EZUK4NCAFNATATFFQYDFZIVNUQJE5TV4"
account_a_mnemonic = "acquire atom pill sustain drum siege rifle nephew guard shadow misery people seek hen awful universe detect arctic mushroom ball device logic athlete ability van"
account_b_address = "SVCT7U7RZEGMBV7QORFKSWC3U27CYKICVG67W7DQ35TOCDB3WAGJXWFP3M"
account_b_mnemonic = "mixture oven shrug payment device clown pony whale hedgehog weekend swarm despair beyond damp obvious primary olive solid unit noble innocent certain conduct absent luxury"
account_c_address = "GVPNGHFMZAFO3ZWXJKQ532T562RJOY7HMCY3PX7BVIVED5SMZXP5ECCWX4"
account_c_mnemonic = "lawsuit mechanic loan tide indoor mixed blue agent act creek found render true foil tone write suit umbrella aspect primary great noble give about catch"
ASA_1 = 74
ASA_1 = 75
pool_1 = None
pool_2 = None
